// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-authorisation/v2/identityclient"
	"net/http"
	"sync"
)

// Ensure, that IdentityInterfaceMock does implement identityclient.IdentityInterface.
// If this is not the case, regenerate this file with moq.
var _ identityclient.IdentityInterface = &IdentityInterfaceMock{}

// IdentityInterfaceMock is a mock implementation of identityclient.IdentityInterface.
//
// 	func TestSomethingThatUsesIdentityInterface(t *testing.T) {
//
// 		// make and configure a mocked identityclient.IdentityInterface
// 		mockedIdentityInterface := &IdentityInterfaceMock{
// 			GetFunc: func(ctx context.Context, url string) (*http.Response, error) {
// 				panic("mock out the Get method")
// 			},
// 		}
//
// 		// use mockedIdentityInterface in code that requires identityclient.IdentityInterface
// 		// and then make assertions.
//
// 	}
type IdentityInterfaceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, url string) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// URL is the url argument value.
			URL string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *IdentityInterfaceMock) Get(ctx context.Context, url string) (*http.Response, error) {
	if mock.GetFunc == nil {
		panic("IdentityInterfaceMock.GetFunc: method is nil but IdentityInterface.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		URL string
	}{
		Ctx: ctx,
		URL: url,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, url)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedIdentityInterface.GetCalls())
func (mock *IdentityInterfaceMock) GetCalls() []struct {
	Ctx context.Context
	URL string
} {
	var calls []struct {
		Ctx context.Context
		URL string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
