---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest

inputs:
  - name: dp-authorisation
    path: dp-authorisation

run:
  path: dp-authorisation/ci/scripts/build.sh
